# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: gitsnip

before:
  hooks:
    - go mod tidy

builds:
  - id: gitsnip
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/dagimg-dot/gitsnip/internal/cli.version={{.Version}} -X github.com/dagimg-dot/gitsnip/internal/cli.commit={{.Commit}} -X github.com/dagimg-dot/gitsnip/internal/cli.buildDate={{.Date}} -X github.com/dagimg-dot/gitsnip/internal/cli.builtBy=goreleaser
    main: ./cmd/gitsnip
    binary: gitsnip

archives:
  - id: gitsnip
    ids: [gitsnip]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: dagimg-dot
    name: gitsnip
